In [208]:
import numpy as np
import pandas as pd
import seaborn as sns

In [209]:
df = pd.read_csv('heart (1).csv')

In [210]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [211]:
df.duplicated().sum()

np.int64(0)

In [212]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

In [213]:
cols = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

for col in df.columns:
    df[col] = Le.fit_transform(df[col])

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,12,1,1,41,147,0,1,98,0,10,2,0
1,21,0,2,55,40,0,1,82,0,20,1,1
2,9,1,1,31,141,0,2,25,0,10,2,0
3,20,0,0,39,72,0,1,34,1,25,1,1
4,26,1,2,49,53,0,1,48,0,10,2,0

In [214]:
from re import X
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

In [215]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [216]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [217]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [218]:
modelLr = LogisticRegression()
modelLr.fit(X_train, y_train)

LogisticRegression()

In [219]:
y_pred = modelLr.predict(X_test)
accuracy_score(y_test, y_pred)

0.8369565217391305

In [220]:
modelSVC = SVC()
modelSVC.fit(X_train, y_train)

SVC()

In [221]:
y_pred = modelSVC.predict(X_test)
accuracy_score(y_test, y_pred)

0.8586956521739131

In [222]:
modelForest = RandomForestClassifier(n_estimators=100,max_depth=None)
modelForest.fit(X_train, y_train)

RandomForestClassifier()

In [223]:
y_pred = modelForest.predict(X_test)
accuracy_score(y_test, y_pred)

0.8858695652173914

In [224]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [225]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X)

In [226]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

In [227]:
LogisticPca = LogisticRegression()
LogisticPca.fit(X_train_pca, y_train)

LogisticRegression()

In [228]:
y_pred = LogisticPca.predict(X_test_pca)
accuracy_score(y_test, y_pred)

0.8315217391304348

In [229]:
SVCpca = SVC()
SVCpca.fit(X_train_pca, y_train)

SVC()

In [230]:
y_pred = SVCpca.predict(X_test_pca)
accuracy_score(y_test, y_pred)
#

0.8586956521739131

In [231]:
ForestPca = RandomForestClassifier(n_estimators=100,max_depth=None)
ForestPca.fit(X_train_pca, y_train)

RandomForestClassifier()

In [232]:
y_pred = ForestPca.predict(X_test_pca)
accuracy_score(y_test, y_pred)
#

0.8260869565217391

In [236]:
X

array([[-1.4331398 ,  0.51595242,  0.22903206, ..., -0.8235563 ,
        -0.87246276,  1.05211381],
       [-0.47848359, -1.93816322,  1.27505906, ..., -0.8235563 ,
         0.12037326, -0.59607813],
       [-1.75135854,  0.51595242,  0.22903206, ..., -0.8235563 ,
        -0.87246276,  1.05211381],
       ...,
       [ 0.37009972,  0.51595242, -0.81699495, ...,  1.21424608,
         0.31894046, -0.59607813],
       [ 0.37009972, -1.93816322,  0.22903206, ..., -0.8235563 ,
        -0.87246276, -0.59607813],
       [-1.64528563,  0.51595242,  1.27505906, ..., -0.8235563 ,
        -0.87246276,  1.05211381]])

In [234]:
X_pca

array([[-2.2382244 ,  0.48416245, -0.34696398,  0.5327096 ],
       [-1.05256754,  0.91704276,  1.38624469,  0.20075612],
       [-1.12919456, -1.03157605, -0.72706585,  1.94792734],
       ...,
       [ 1.70757735, -0.63771181, -0.82201641,  0.10419136],
       [-1.68191429,  1.53589391,  0.43837591, -0.84786119],
       [-2.47905477, -0.70285966,  0.08526573, -0.19800125]])